### ISSUE TITLE
Hardhat support

### ISSUE THREAD

**Issue by lost-theory** [ApeWorX/ape#130]
### Elevator pitch:

Add support for [Hardhat](https://hardhat.org/) as a network provider in Ape.

### Value:

Hardhat is an Ethereum development environment written in JavaScript that includes a JSON RPC node. We can use this endpoint as a network provider (as an alternative to existing eth-tester, Infura, and HTTP network providers). The Hardhat node has a few extra features that are useful for Ape developers, like a fork mode and snapshots (esp. useful for writing test code).

### Dependencies:

N/A.

### Design approach:

Should be straightforward to implement using the existing HTTP provider (`EthereumProvider`) and possibly looking at Brownie's hardhat support:

https://github.com/eth-brownie/brownie/blob/master/brownie/network/rpc/hardhat.py

### Task list:

* [x] Implementation the basic provider and abstract methods (get balance, send transaction, etc.)
* [x] Implement the custom hardhat methods (sleep, mine, snapshot, revert, impersonate, etc.)
* [x] Tests for all of the above

### Estimated completion date:

Mid August 2021.

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)
