### ISSUE TITLE
Plugins Ongoing Improvement Tracking Ticket

### ISSUE THREAD

**Issue by unparalleled-js** [ApeWorX/ape#245]
Chris and I are making a list of improvements to the plugins commands

---

- [ ] Track if plugins that did not load correctly and don't include them in the `available plugins
- [ ] Display if a plugin got uninstalled correctly.
- [ ] Able to uninstall all plugins from an `ape-config.yaml` file (this is really helpful for developers testing out plugins lol)
- [ ] Iline 96 `if display_all` could just be `else`.
- [ ] Refactor: Move logic that builds up the output to the `PluginManager`. Then, all the CLI does it call into that and maybe check a few other things regarding edge cases. This will also help the `ape console` because it can then easily see the same output without having to exit the console first.
- [ ] Handle multiword plugin names by converting underscore to hyphen (just use `clean_method_name()` method).
For example, `ape-tq-tezos` (doesn't actually exist) should be `ape plugins add tq-tezos`. The package will be named `ape_tq_tezos` however.

**Comment by Ninjagod1251** [comment]
I would like a way to update plugins via ape commands

**Comment by fubuloubu** [comment]
> There was an issue with installing ape-token via `ape plugins add tokens`
> 
> ```
> WARNING: Error loading plugin package 'ape_tokens'.
>         ImportError: cannot import name 'SIGNED_INTEGERS' from 'ape.managers.converters' (/home/chris/ape/src/ape/managers/converters.py)
>         (Use `--verbosity DEBUG` to see full stack-trace)
> ```

This should be fixed now!

**Comment by Ninjagod1251** [comment]
yes i confirmed it with jules thank you!

**Comment by Ninjagod1251** [comment]
edge case: If you want to install or uninstall a list of plugins and you are in the WRONG Current Working Directory

we should prompt the user that the program tried to find the list of plugins at this current working directory. so they know why the list of installed plugins did not change.

**Comment by unparalleled-js** [comment]
This one is really important!  https://github.com/ApeWorX/ape/issues/269

It has its own ticket but follows the same sentiment

**Comment by unparalleled-js** [comment]
This one is also related: https://github.com/ApeWorX/ape/issues/383
