### ISSUE TITLE
Plugins: Add `QueryAPI` plugin types

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#390]
### Elevator pitch:
We want to add queries to `ape`, but need an abstraction for different query engines (e.g. brute force, sqlite, posgres, mongodb, etc.) to perform those queries

### Value:
Data workflows including `Querying:` work items

### Dependencies:
Pydantic Refactor: #126

### Design approach:
```py
class QueryAPI(APIDefinition):
    chain: ChainManager  # access to `active_provider`, `blocks` and other chain properties for performing queries
    config: ConfigItem  # Including DB connection info

    @apimethod
    def can_execute(query: QueryRequest) -> bool:
        """
        Returns True if this plugin can perform the given query.
        """

    @apimethod
    def execute(query: QueryRequest) -> QueryResult:
        """
        Run query and return the results
        """
```

where `QueryRequest` contains an abstracted query using raw/`ape.api`/`ape.types` types (e.g. `BlockAPI`, `TransactionAPI`),
and `QueryResult` contains a dataset (using numpy `ndarray` types, etc.) and query properties (for joining queries, etc.)

NOTE: `QueryResult` can perhaps be lazily-generated, so that when merged with other queries to form more complex queries, they can be performed more efficiently than brute force. (Perhaps `QueryRequest` is a proper subset of `QueryResult`?)

NOTE: `QueryRequest` and `QueryResult` can use existing Python abstractions around these types of workflows, such as `SQLAlchemy`, `PyTorch`, etc. Whatever is the best solution here.

NOTE: Allow config to specify which `QueryAPI` classes to use to perform queries

TODO: Do we need a `QueryManager` object to manage the plugins?

### Task list:
* [ ] Research numpy and query libraries like `SQLAlchemy`, especially in relationship to `Pydantic`
* [ ] Implement "brute force" plugin in ape core, which simply performs any relevant queries with calls to `active_provider` and in-memory handling (will be default for "real-time" queries that might take place over new blocks)
* [ ] Implement sqlite 2nd party plugin to perform queries using on-disk sqlite db.
* [ ] Research postgres 2nd party plugin to perform queries using local and/or remote postgres db
* [ ] Research [Vulcanize](https://github.com/vulcanize) and/or [TrueBlocks](https://github.com/trueblocks) 2nd/3rd party plugins

### Estimated completion date:
Feb 4th, 2021

### Design review:
Reviewers: @evanblank3 @unparalleled-js 

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by johnson2427** [comment]
SQLAlchemy is a powerful tool. It's used in Apache Superset -> https://superset.apache.org/ -> https://github.com/apache/superset

I use this with Pydantic in FastAPI. There is a minus to this though. You have to know your schema. So if you are developing a plugin, you have to bring your own schema into this. But, SQLAlchemy has the ability to connect to quite a few databases

https://docs.sqlalchemy.org/en/14/dialects/

I also have a lot of experience with NoSQL (MongoDB specifically) if we wanted to be able to find collections in Mongo, we could add that too
I also have a lot of experience working with Postgres.

**Comment by fubuloubu** [comment]
> I use this with Pydantic in FastAPI. There is a minus to this though. You have to know your schema. So if you are developing a plugin, you have to bring your own schema into this. But, SQLAlchemy has the ability to connect to quite a few databases

Totally agree. Was thinking that the API classes would be the schema types as well, e.g. `BlockAPI`, `TransactionAPI`, etc. would be sqlalchemy data models

**Comment by fubuloubu** [comment]
Also yes, using NoSQL on disk as default db would be fine. And then postgres connection as a secondary plugin, TrueBlocks, VulcanizeDB, google cloud ethereum db, etc,

**Comment by johnson2427** [comment]
The NoSQL solution is a nice one, because it eliminates the need for creating a schema. If endpoints change available data, it'll break our SQL solution (unless we just dump JSON into a column, which most SQL solutions can).

But for the schema to be created, yeah, you'd have to leave it as a abstractdataclass and then force the user to create their schemas. Pydantic implementation looks something like this for the Schema.

```python
# from typing import Optional, List
import datetime

from pydantic import BaseModel
from typing import List


class DateRequest(BaseModel):
    dates: List[str]


class ContestDataBase(BaseModel):
    date: datetime.date


class ContestDataCreate(ContestDataBase):
    time: datetime.time
    site: str
    contest_name: str
    winning_chart: dict
    entries: List[float]


class ContestData(ContestDataBase):
    time: datetime.time
    site: str
    contest_name: str
    winning_chart: dict
    entries: list

    class Config:
        orm_mode = True
```
And then something like this for a model.py
```python
from sqlalchemy import Boolean, Column, ForeignKey, Integer, String, Date, Time, Float, JSON, ARRAY

from apollo.backend.database.db import Base


class ContestData(Base):
    __tablename__ = "contest_data"

    date = Column(Date, index=True)
    time = Column(Time, index=True)
    site = Column(String, index=True)
    contest_name = Column(String, index=True)
    winning_chart = Column(JSON, index=True)
    entries = Column(ARRAY(Float), index=True)
```
And this is just for 1 table.

**Comment by unparalleled-js** [comment]
How do these off-chain databases get populated?

**Comment by unparalleled-js** [comment]
Rather than checking if a plugin can perform the query, could we call the plugin by name?

Something like `queries.<plugin_name>.execute(my_query)`

The user has to be more explicit about which engine to use, especially when they have multiple plugins that can execute the same type of query.

**Comment by fubuloubu** [comment]
> How do these off-chain databases get populated?

lots and lots of indexing time

**Comment by fubuloubu** [comment]
> Rather than checking if a plugin can perform the query, could we call the plugin by name?
> 
> Something like `queries.<plugin_name>.execute(my_query)`
> 
> The user has to be more explicit about which engine to use, especially when they have multiple plugins that can execute the same type of query.

So the main interface for users would be the `.query("param1,param2", **query_args)` methods on `BlockContainer`, etc. This API would be how queries are routed internally of that method. Perhaps it would be nice to be able to specify the query engine, something like `.query("param1,param2", plugin=<plugin_name>, **query_args)`

**Comment by johnson2427** [comment]
Are we interested in GraphQL queries for this? Not sure how many subgraphs there are, but we could create our own subgraphs, and many have been built out already -> https://thegraph.com/explorer

**Comment by unparalleled-js** [comment]
> Are we interested in GraphQL queries for this? Not sure how many subgraphs there are, but we could create our own subgraphs, and many have been built out already -> https://thegraph.com/explorer

I don't see why not!

**Comment by johnson2427** [comment]
I'm just not sure how we want to build this out. I started a plugin for this, set up the backbone, then realized, we are going to need a ton of queries for this, so maybe it needs to be organized in multiple plugins? I'm not sure, we have to map out what we want to query.

**Comment by fubuloubu** [comment]
> Are we interested in GraphQL queries for this? Not sure how many subgraphs there are, but we could create our own subgraphs, and many have been built out already -> https://thegraph.com/explorer

Yes actually, I think Graph would be an excellent 2nd party plugin!

**Comment by unparalleled-js** [comment]
Thanks @johnson2427
