### ISSUE TITLE
Querying: allow block-series `.query` method on the `BlockContainer` object in `chain` manager

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#391]
### Elevator pitch:
Be able to form datasets from querying a parameter from `BlockAPI` over a specified range of blocks.

For example:
```py
# Average value of `base_fee` over all blocks since `N`
avg_base_fee = math.avg(chain.blocks.query("base_fee", start_block=N))

# Set of all miners that mined all blocks since `N`
miners: NumpyArray[AddressType] = set(chain.blocks.query("coinbase", start_block=N))
```

### Value:
This is valuable for data scientists who quickly want to perform an efficient query over a range of blocks to obtain a timeseries dataset.

### Dependencies:
In order to be efficient, significant caching is necessary, coupled with an archive node for historical retrieval. Explore making these types of queries as efficient as possible.

### Design approach:
```py
class BlockContainer:
    def query(self, *args, **kwargs):
        # Encode the call w/ *args
        ...
        # Perform query using ProviderAPI over `kwargs` query args
        ...
```

### Task list:
- [ ] Explore fundamental data model for query results (`numpy`?)
- [ ] Explore `ProviderAPI` updates to make historical queries
- [ ] Design `kwargs` specification for query filter parameters (e.g. `start_block`, `end_block`, etc.)
- [ ] Explore `QueryAPI` updates to speed up historical queries

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by fubuloubu** [comment]
Related: #390
