### ISSUE TITLE
Querying: allow block-series `.query` method on any `TxnHistoryContainer` object

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#392]
### Elevator pitch:
Be able to form datasets from querying a parameter from `TransactionAPI` over a specified set of Transactions.

For example:
```py
# Total Fees over all transactions ever made by an account
account_fees = sum(chain.history[account].query("total_fee"))

# Total Fees over all transactions made on the chain over since block `N`
total_fees = sum(chain.history.query("total_fee", start_block=N))
```

### Value:
This is valuable for data scientists who quickly want to perform an efficient query over a set of transactions to obtain datasets for other uses.

### Dependencies:
In order to be efficient, significant caching is necessary, coupled with an archive node for historical retrieval. Explore making these types of queries as efficient as possible.

### Design approach:
```py
class TxnHistoryContainer:
    def query(self, *args, **kwargs):
        # Encode the call w/ *args
        ...
        # Perform query using ProviderAPI over `kwargs` query args
        ...
```

### Task list:
- [ ] Explore fundamental data model for query results (`numpy`?)
- [ ] Explore `ProviderAPI` updates to make historical queries
- [ ] Design `kwargs` specification for query filter parameters (e.g. `start_block`, `end_block`, etc.)
- [ ] Explore `QueryAPI` updates to speed up historical queries

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by fubuloubu** [comment]
Related: #390
