### ISSUE TITLE
Testing: Display Trace

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#700]
### Elevator pitch:
Print a Tree

### Value:
It is often very nice to be able to print out a trace of the call tree made during a transaction for debugging purposes, or displaying stack traces when a revert occurs. Here are some examples in various frameworks:

Brownie:
https://eth-brownie.readthedocs.io/en/stable/core-transactions.html?highlight=trace#call-traces
(added in https://github.com/eth-brownie/brownie/pull/679)

Foundry:
ipfs://bafybeihapxqz43vadpqicxulwihrj6pqnvrxavf7hruk6xk45es57ds3hi/forge/traces.html

Hardhat:
https://hardhat.org/hardhat-network/#solidity-stack-traces

### Dependencies:
- Using https://github.com/ApeWorX/evm-trace
- https://github.com/ApeWorX/ape/tree/feat/tracing @NotPeopling2day's branch

### Design approach:
Add `ReceiptAPI.show_trace()` (TBD naming) to print the raw tree, then make the tree pretty

### Task list:
- [ ] Print raw tree (showing addresses and calldata of unknown contract types)
- [ ] "Lift" tree by finding contract types we know (either from Etherscan or our internal deployments) and ABI decoding
- [ ] Pretty-print "lifted" call tree

### Estimated completion date:
Friday 5/13

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by unparalleled-js** [comment]
Blocked by this: https://github.com/ApeWorX/ape/issues/374

Need behind-the-scenes caching of local deployments.

**Comment by unparalleled-js** [comment]
Working on Parity support
