### ISSUE TITLE
Query: Flatten BlockAPI and migrate to Transaction/Blocks Types

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#701]
### Elevator pitch:
For database work, we want `TransactionAPI` and `BlockAPI` to be non-abstract types instead of api classes

### Value:
Remove them as API classes allows a cleaner refactor in prep for query engine work

### Dependencies:
N/A

### Design approach:
See Task List

### Task list:

- [x] Flatten `BlockAPI` structure (remove `GasDataAPI` and `ConsensusAPI`)
- [x] Migrate `TransactionAPI.serialize_transaction` to `EcosystemAPI`
- [ ] ~~Migrate `ReceiptAPI` and `BlockAPI` to `ape.types` and subclass `BaseModel` instead of `BaseInterfaceModel`~~

### Estimated completion date:
Weds 5/11

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by johnson2427** [comment]
I'm hung up on the last part here for the TransactionAPI

**Comment by fubuloubu** [comment]
We may need to work with @unparalleled-js on this

**Comment by unparalleled-js** [comment]
The third part seems good to be so long as Ecosystem plugins can still subclass the `TransactionAPI` and `BlockAPI` classes.

> I'm hung up on the last part here for the TransactionAPI

What about?

> We may need to work with @unparalleled-js on this

👋🏻

**Comment by fubuloubu** [comment]
> so long as Ecosystem plugins can still subclass the `TransactionAPI` and `BlockAPI` classes.

This is actually the part we might need to work with you on changing

**Comment by unparalleled-js** [comment]
> This is actually the part we might need to work with you on changing

Schedule some time on my calendar! Or else, draft a spec and send it to me and I will let you know if it will work for Starknet. (Is this about Starknet?)

**Comment by johnson2427** [comment]
> The third part seems good to be so long as Ecosystem plugins can still subclass the `TransactionAPI` and `BlockAPI` classes.
> 
> > I'm hung up on the last part here for the TransactionAPI
> 
> What about?
> 
> > We may need to work with @unparalleled-js on this
> 
> 👋🏻

Sorry for the late response here, had a long day with doctor's appointments.  I am going to pull BlocksAPI and TransactionAPI over to ape.types. Not sure if I make two separate files for these two. Also moving to BaseModel, I'm struggling to figure out how to implement that without breaking everything

**Comment by fubuloubu** [comment]
> > The third part seems good to be so long as Ecosystem plugins can still subclass the `TransactionAPI` and `BlockAPI` classes.
> > > I'm hung up on the last part here for the TransactionAPI
> > 
> > 
> > What about?
> > > We may need to work with @unparalleled-js on this
> > 
> > 
> > 👋🏻
> 
> Sorry for the late response here, had a long day with doctor's appointments. I am going to pull BlocksAPI and TransactionAPI over to ape.types. Not sure if I make two separate files for these two. Also moving to BaseModel, I'm struggling to figure out how to implement that without breaking everything

Yes, this is the thing we need to figure out. I think let's start with the breaking change to the fields in `TransactionAPI`/`BlockAPI` first in one PR, then open another PR based off the first when we agree on the approach for removing the dependency issues
