### ISSUE TITLE
Package: Add `.references` and `.imports` to `PackageManifest` under `ProjectManager`

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#704]
### Elevator pitch:
Save the references and imports under the current project on each call to compile

### Value:
Contract verification

### Dependencies:
https://github.com/ApeWorX/ethpm-types/pull/30

### Design approach:
n/a

### Task list:
- [x] Update `CompilerAPI` to add `.fetch_imports(self, paths: List[Path], base_path: Path = None) -> {SourceId: List[SourceId]}`
- [x] Inject `.imports` for each `SourceId` into the related `Source` object
- [x] Append `SourceId` into `.references` for each import

### Estimated completion date:
05/11

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by unparalleled-js** [comment]
@NotPeopling2day I believe this was done in https://github.com/ApeWorX/ape/pull/730
Can this be closed?

**Comment by NotPeopling2day** [comment]
The core functionality exists and individual compiler plugins will implement the logic for gathering imports from the contracts.
