### ISSUE TITLE
Add Transaction Query support

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape#727]
### Elevator pitch:
It's useful to be able to query for transactions in multiple contexts (in terms of the account who made it, the block it's included in, etc.)

### Value:
Be able to implement query functionality across transactions.
This will help implement #392

### Dependencies:
N/A

### Task list:
* [x] Merge `ape.api.query._BaseAccountQuery` into `ape.api.query.AccountQuery`
* [x] Refactor `ape.api.query.AccountQuery` to `ape.api.query.AccountTransactionQuery`
* [x] Add `ape.api.query.BlockTransactionQuery` where `block_id` is the filter applied
* [x] Add support into `ape.managers.query.DefaultQueryProvider`
* [ ] Integrate into `ape_cache.query.CacheQueryProvider` #680 

### Estimated completion date:
5/20/2022

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by fubuloubu** [comment]
Modification to `BlockAPI`:

```py
class BlockAPI:
    ...
    # remove `transaction_ids`
    num_transactions: int = 0
```

Implemention `BlockTransactionQuery`:

```py
class BlockTransactionQuery(_BaseQuery):
    block_id: Hash

    @classmethod
    def all_fields(cls) -> List[str]:
        return list(TransactionAPI.__fields__)
```

Added to `BlockAPI`:
```py
    @cached_property
    def transactions(self) -> List[TransactionAPI]:
        query = BlockTransactionQuery(block_id=self.hash)
        txns_dataframe = self.query_manager.query(query)
        return # convert `txns_dataframe` into `List[TransactionAPI]`
```

How to do query by defualt:
```py
class DefaultQueryProvider:
    ...

    def perform_query(query: BlockTransactionQuery) -> pd.Dataframe:
         # ProviderAPI.get_transactions_for_block(block_id: Hash) -> Iterator[TransactionAPI]
         transactions_iter = self.provider.get_transactions_for_block(query.block_id)
         # return transactions as a dataframe
```

https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.get_block_transaction_count
https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.get_transaction_by_block

**Comment by fubuloubu** [comment]
> We are moving everything from `_BaseAccountQuery` into `AccountQuery` and then removing `_BaseAccountQuery`.

Correct

> Then we are moving all functionality from `AccountQuery` to a new class that does not currently exist `AccountTransactionQuery`. Is this correct?

Yes, but just change the name

> Also, we are doing that for BlockQuery as well.

No, I think that's okay. It would be making a new class `BlockTransactionQuery` (separate from `BlockQuery`) that queries for transactions from a block

**Comment by johnson2427** [comment]
> Modification to `BlockAPI`:
> 
> ```python
> class BlockAPI:
>     ...
>     # remove `transaction_ids`
>     num_transactions: int = 0
> ```
> 
> Implemention `BlockTransactionQuery`:
> 
> ```python
> class BlockTransactionQuery(_BaseQuery):
>     block_id: Hash
> 
>     @classmethod
>     def all_fields(cls) -> List[str]:
>         return list(TransactionAPI.__fields__)
> ```
> 
> Added to `BlockAPI`:
> 
> ```python
>     @cached_property
>     def transactions(self) -> List[TransactionAPI]:
>         query = BlockTransactionQuery(block_id=self.hash)
>         txns_dataframe = self.query_manager.query(query)
>         return # convert `txns_dataframe` into `List[TransactionAPI]`
> ```
This creates a circular import
> 
> How to do query by defualt:
> 
> ```python
> class DefaultQueryProvider:
>     ...
> 
>     def perform_query(query: BlockTransactionQuery) -> pd.Dataframe:
>          # ProviderAPI.get_transactions_for_block(block_id: Hash) -> Iterator[TransactionAPI]
>          transactions_iter = self.provider.get_transactions_for_block(query.block_id)
>          # return transactions as a dataframe
> ```
> 
> https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.get_block_transaction_count https://web3py.readthedocs.io/en/stable/web3.eth.html#web3.eth.Eth.get_transaction_by_block

Not sure what the best way to mitigate this at the moment

**Comment by fubuloubu** [comment]
> This creates a circular import
> 
> Not sure what the best way to mitigate this at the moment

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from <wherever> import TransactionAPI

...

    @cached_property
    def transactions(self) -> List["TransactionAPI"]:  # This differs mypy checking
        ...
```

see https://docs.python.org/3/library/typing.html#typing.TYPE_CHECKING

**Comment by fubuloubu** [comment]
> By ` Add support into ape.managers.query.DefaultQueryProvider` are we talking about `BlockTransactionQuery` for right now?

yes!

**Comment by johnson2427** [comment]
Just checking, thank you!
