### ISSUE TITLE
Remove return of pandas DataFrames from DefaultQueryProvider

### ISSUE THREAD

**Issue by johnson2427** [ApeWorX/ape#766]
### Elevator pitch:

Currently, DataFrames are used as the canonical way of passing data via `QueryAPI` plugins. Because of this, data is lost when filtering down on specific columns in the data sets, and it's more inefficient overall because the data must be converted back and forth many times.

### Value:

This is currently causing issues with encoding and decoding for current work item: #732 

### Dependencies:

@johnson2427 

### Design approach:

Remove pandas DataFrame returns from `QueryAPI` plugins and the `QueryManager` class. The externally-facing methods that return DataFrame objects (such as [here](https://github.com/ApeWorX/ape/blob/91c27a1b3ad0d5a3a085fa318ec72b92eb3a63c1/src/ape/managers/chain.py#L91)) will be kept as-is to support those use cases without any breaking changes

### Task list:

* [x] Remove pd.DataFrame(...) returns
* [x] Fix methods that unpack and reformat these DataFrames
* [x] Check tests work

### Estimated completion date:
June 3rd, 2022

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by fubuloubu** [comment]
Signed off
