### ISSUE TITLE
Compiler Information field not stored in package manifest

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#792]
### Elevator pitch:
Add compiler settings and version information to manifest for publishing use cases

### Value:
Publishing a manifest, publishing files from a project (e.g. Etherscan verification)

### Dependencies:
Contract manifest requires compiler to be filled in to be more useful and for contract verification https://github.com/ApeWorX/ape/issues/81

### Design approach:
EIP-2678 defines an array of [`CompilerInformation`](https://eips.ethereum.org/EIPS/eip-2678#the-compiler-information-object) objects that are referenced by `Source` objects within the same manifest. These objects are used to determine which compiler types, versions, and settings that should be used to compile the (sub-)set of sources for a given manifest.

Using EIP-2678 (or adapting for our needs via #794), add support for obtaining the information for this field in `ProjectManager` and `CompilerAPI` so that we have it for later use. The current structure may be inadequate for our purposes, requiring a breaking change to `ethpm-types` that should be targeted for v0.3.0 if possible.

### Task list:
* [ ] Identify compilation process for projects
* [ ] Obtain compiler version and setting information for each (sub-)set of files to be compiled
* [ ] Leverage this information for calling each compiler (in series) to obtain the various results

### Estimated completion date:
TBD

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by fubuloubu** [comment]
p.s. next time use `Work Item` issue template for this kind of thing

**Comment by sabotagebeats** [comment]
dependency for vyper: https://github.com/ApeWorX/ape/issues/850

**Comment by sabotagebeats** [comment]
in progress: blocked by issue #850

**Comment by unparalleled-js** [comment]
> in progress: blocked by issue #850

See latest comment! Not necessarily blocked.

Also - let's get Solidity out the door since it is in-progress and then return to vyper

[status update from retro]

**Comment by sabotagebeats** [comment]
In progress. Needs refactor to place data correctly.

**Comment by sabotagebeats** [comment]
merged. requires tests to be merged.
