### ISSUE TITLE
Meta field not stored in contract manifest

### ISSUE THREAD

**Issue by sabotagebeats** [ApeWorX/ape#793]
### Elevator pitch:
Add project name, version, and meta fields from `ape-config.yaml` to the package manifest for a project

### Value:
Publishing a manifest, publishing files from a project (e.g. Etherscan verification)

### Dependencies:
Meta information in contract manifest needs to be filled in as per EIP spec to do contract verification #81 

### Design approach:
EIP-2678 defines the project name, version, and a [`package meta`](https://eips.ethereum.org/EIPS/eip-2678#the-package-meta-object) object that should be added to ethPM manifests that will be published. This will typically contain important information used for indexing purposes as well as licensing info, authorship, links, etc. that are recommended for publishing.

Package name and version are already fields present in `CompilerManager` that get parsed through the `ape-config.yaml` config file:
https://github.com/ApeWorX/ape/blob/74d659feea35cf2266478851832bddd2e9a8b5e7/src/ape/managers/config.py#L83-L87

However, the meta object needs to be added to config (mirroring EIP-2678) so it can be copied appropiately to the project's manifest file when ready to publish. We had commented out code that was supposed to achieve this here:
https://github.com/ApeWorX/ape/blob/74d659feea35cf2266478851832bddd2e9a8b5e7/src/ape/managers/project/manager.py#L450-L462

### Task list:
* [ ] Uncomment the linked code and ensure it functions properly w/ `name` and `version` from the config
* [ ] Add the `meta` field to the `ConfigManager` object (imported from [here](https://github.com/ApeWorX/ethpm-types/blob/main/ethpm_types/manifest.py#L48))
* [ ] Verify that a fully complete manifest can be produced for any project

### Estimated completion date:
June 10th

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by fubuloubu** [comment]
@sabotagebeats please try to complete this one first! It should be fairly easy, I've laid out the steps in the task list

**Comment by sabotagebeats** [comment]
`src/ape/managers/project/manager.py:452: error: "PluginConfig" has no attribute "serialize"`
