### ISSUE TITLE
Nightly Integration Test Builds

### ISSUE THREAD

**Issue by NotPeopling2day** [ApeWorX/ape#919]
### Elevator pitch:

Create a process for testing integration of core and plugins to auto run nightly.
### Value:

Ape DevZ et al.

### Design approach:

- Use the main branch of ape core and all plugins, unreleased
- Optional: Don't run if no changes (if it's easy to determine changes or not)
  - https://stackoverflow.com/questions/63014786/how-to-schedule-a-github-actions-nightly-build-but-run-it-only-when-there-where 
- Notify if dependency versions break
- Run test ad hoc: manually triggered but auto nightly

Determine whether to do:
- Github action/script within ape repo
- Testing repo specific to integrations

### Task list:

* [ ] Install all plugins
* [ ] Verify all installed correctly
* [ ] Use/access each plugin with simple tests i.e. ENS convert name to address
* [ ] Mark nightly for subset of tests

### Design review:

Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)
